"""Make unit code unique per course, not globally

Revision ID: 9e76790a6b6c
Revises: edf604197c68
Create Date: 2025-06-19 13:29:14.562648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e76790a6b6c'
down_revision = 'edf604197c68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.drop_constraint('code', type_='unique')
        batch_op.create_unique_constraint('uq_code_course', ['code', 'course_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.drop_constraint('uq_code_course', type_='unique')
        batch_op.create_unique_constraint('code', ['code'])

    # ### end Alembic commands ###
